### ISSUE TITLE
How to implement shading editing and relighting in the paper?

### ISSUE THREAD

**Issue by yunchao-ding** [compphoto/Intrinsic#1]
Hi,
Thank you very much for your work. If you want to implement color editing and relighting in the paper, how to achieve it? I didn't find this function in the published code.

**Comment by CCareaga** [comment]
Hi, 

I've added a [Colab notebook](https://github.com/compphoto/Intrinsic/blob/main/recoloring.ipynb) and [the data](https://github.com/compphoto/Intrinsic/tree/main/examples) used to generate the recoloring examples seen in Figure 21 of our paper.  
<a target="_blank" href="https://colab.research.google.com/github/compphoto/Intrinsic/blob/main/recoloring.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

As for the relighting, the process is more involved, and I did not create those results just using Python. The results were rendered from Blender using estimated normals from [omnidata](https://github.com/EPFL-VILAB/omnidata). I have attached an archive containing an example Blender script and the inputs used to generate one of the examples in our paper. I created the paper figures using an older version of Blender and I noticed the results look slightly different in Blender 4.0 ( I had to adjust the normal strength parameter to 0.5 to make it look correct). But hopefully that gives a rough idea of how I generated the results. I replaced the albedo in the node editor to generate results for different methods (make sure the colorspace is correct for the loaded image). 

[relight_example_github.zip](https://github.com/compphoto/Intrinsic/files/13835165/relight_example_github.zip)

**Comment by yunchao-ding** [comment]
> Hi,
> 
> I've added a [Colab notebook](https://github.com/compphoto/Intrinsic/blob/main/recoloring.ipynb) and [the data](https://github.com/compphoto/Intrinsic/tree/main/examples) used to generate the recoloring examples seen in Figure 21 of our paper. [ ![Open In Colab](https://camo.githubusercontent.com/f5e0d0538a9c2972b5d413e0ace04cecd8efd828d133133933dfffec282a4e1b/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667) ](https://colab.research.google.com/github/compphoto/Intrinsic/blob/main/recoloring.ipynb)
> 
> As for the relighting, the process is more involved, and I did not create those results just using Python. The results were rendered from Blender using estimated normals from [omnidata](https://github.com/EPFL-VILAB/omnidata). I have attached an archive containing an example Blender script and the inputs used to generate one of the examples in our paper. I created the paper figures using an older version of Blender and I noticed the results look slightly different in Blender 4.0 ( I had to adjust the normal strength parameter to 0.5 to make it look correct). But hopefully that gives a rough idea of how I generated the results. I replaced the albedo in the node editor to generate results for different methods (make sure the colorspace is correct for the loaded image).
> 
> [relight_example_github.zip](https://github.com/compphoto/Intrinsic/files/13835165/relight_example_github.zip)

Thank you very much for sharing! I was inspired by this.
