### ISSUE TITLE
Release Intrinsic models on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [compphoto/Intrinsic#10]
Hello @CCareaga 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered through AK's daily papers as yours got featured: https://huggingface.co/papers/2409.13690. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance), you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the models you've pre-trained on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) we can provide you an A100 grant.

What do you think?

Kind regards,

Niels

**Comment by CCareaga** [comment]
Hi Niels,

Thank you for the information, I'll look into this and let you know if I have any questions.

**Comment by CCareaga** [comment]
I noticed the ZeroGPU option, which says free but it seems like I have to subscribe to PRO which isn't free right? If so, I will apply for the community grant option.

Thanks for the help

**Comment by CCareaga** [comment]
Hi Niels, 

I forgot to mention, I did get the huggingface space set up and linked to the paper page. I was also granted a ZeroGPU space, so my demo runs well now. Thanks for the help!

**Comment by NielsRogge** [comment]
Ok cool @CCareaga!

FYI the models don't seem to be linked to the paper, would be cool to add them :) https://huggingface.co/docs/hub/en/models-uploading

<img width="1241" alt="Screenshot 2024-11-21 at 18 08 03" src="https://github.com/user-attachments/assets/4be49c53-05de-4a45-8862-58930d7cf414">

as I see they are currently hidden here: https://github.com/compphoto/Intrinsic/blob/4e8a2022a72ce86f2b4807daaf31cab12e39d2bb/intrinsic/pipeline.py#L63-L67
