### ISSUE TITLE
Recoloring notebook raise an import error

### ISSUE THREAD

**Issue by sawyer7246** [compphoto/Intrinsic#13]
Hi, thank you so much for your work.

I've tried the [recoloring notebook](https://github.com/compphoto/Intrinsic/blob/main/recoloring.ipynb), it raised an import error like:
```python
from intrinsic.model_util import load_models
ModuleNotFoundError: No module named 'intrinsic.model_util'
```
then I try to use the `from intrinsic.pipeline import load_models` instead, but there is another error raised like 
```python
----> 1 results = run_pipeline(
      2     intrinsic_model,
      3     inp,
      4     resize_conf=None,
      5     maintain_size=True

TypeError: run_pipeline() got an unexpected keyword argument 'maintain_size'
```
pls help ;)

**Comment by CCareaga** [comment]
I've updated the recoloring notebook so that it runs correctly now, let me know if it raises any errors. Note this is the old version of the pipeline (only grayscale shading) I have not tested recoloring with the updated pipeline, but it should work under more robustly.
