### ISSUE TITLE
No module named 'intrinsic.model_util'

### ISSUE THREAD

**Issue by g8392** [compphoto/Intrinsic#14]
When running the recoloring script I get:

---------------------------------------------------------------------------
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[12], line 9
      7 # import model loading and running the pipeline
      8 from intrinsic.pipeline import run_pipeline
----> 9 from intrinsic.model_util import load_models

ModuleNotFoundError: No module named 'intrinsic.model_util'
```

----

intrinsic inference works fine, but even after following the notebook for recoloring I have this problem with the modules. Using **from intrinsic.pipeline import load_models, run_pipeline** from inference works but then I get:

```
   282 # this is the shading color components, N x 2 x H x W
    283 with torch.no_grad():
--> 284     uv_shd = models['col_model'](inp)
    286 # resize the low res shd chroma back to original size
    287 uv_shd = torch.nn.functional.interpolate(uv_shd, size=orig_sz, mode='bilinear', align_corners=True)

KeyError: 'col_model'
```

**Comment by CCareaga** [comment]
The notebook uses the old version of the pipeline, I have updated the notebook to run without errors.
