### ISSUE TITLE
Get different white balance result using the same input image

### ISSUE THREAD

**Issue by herohuyongtao** [compphoto/Intrinsic#17]
I get the following white balance result (via key `wb_img`) using the same input street sample image given in paper's Fig. 2 (note: image is re-downloaded from [here](https://unsplash.com/photos/a-person-walking-down-a-street-at-night-lXR86Iidf7g)). However, the result appears quite different from what is shown in the paper. Could you clarify if I am missing something? Thanks.

![wb_img](https://github.com/user-attachments/assets/dc604bd9-5e64-4027-b544-519d736aa607)

**Comment by CCareaga** [comment]
Hi,

The image should be linear when sent through our pipeline (and when performing illumination-aware editing in general) so we undo the gamma correction of the input image by raising it to a power of 2.2. What you have visualized is the whitebalanced image without gamma correction applied. To visualize it properly, you can gamma-correct it with `wb_img ** (1/2.2)`

**Comment by herohuyongtao** [comment]
Thanks for the clarification. Now it works as expected.

**Comment by herohuyongtao** [comment]
Thanks for the clarification. Now it works as expected.
