### ISSUE TITLE
Is it possible to provide training and testing datasets?

### ISSUE THREAD

**Issue by xcandxc** [compphoto/Intrinsic#2]
Hi, congratulations on achieving so much. Is it possible to provide training and testing datasets? I want to observe the performance effect of editing through a large number of images.

**Comment by CCareaga** [comment]
Our method is trained and evaluated using public datasets:

Training:
- [Hypersim](https://github.com/apple/ml-hypersim)
- [OpenRooms](https://vilab-ucsd.github.io/ucsd-openrooms/)
- [CGIntrinsics](https://www.cs.cornell.edu/projects/cgintrinsics/)
- [GTA Dataset](https://www.philkr.net/fsv/)
- [MIDIntrinsics](https://yaksoy.github.io/MIDIntrinsics/)

Evaluation:
- [ARAP Dataset](https://perso.liris.cnrs.fr/nicolas.bonneel/intrinsicstar/ground_truth/)
- [IIW Dataset](http://opensurfaces.cs.cornell.edu/intrinsic/)
- [SAW Dataset](http://opensurfaces.cs.cornell.edu/saw/)

**Comment by xcandxc** [comment]
> Our method is trained and evaluated using public datasets:
> 
> Training:
> 
> * [Hypersim](https://github.com/apple/ml-hypersim)
> * [OpenRooms](https://vilab-ucsd.github.io/ucsd-openrooms/)
> * [CGIntrinsics](https://www.cs.cornell.edu/projects/cgintrinsics/)
> * [GTA Dataset](https://www.philkr.net/fsv/)
> * [MIDIntrinsics](https://yaksoy.github.io/MIDIntrinsics/)
> 
> Evaluation:
> 
> * [ARAP Dataset](https://perso.liris.cnrs.fr/nicolas.bonneel/intrinsicstar/ground_truth/)
> * [IIW Dataset](http://opensurfaces.cs.cornell.edu/intrinsic/)
> * [SAW Dataset](http://opensurfaces.cs.cornell.edu/saw/)

Thank you for your help.

**Comment by 23wjj** [comment]
Hello, I try to get the training data of GTA Dataset from the official website, but the one drive link seems to be invalid. Is there any other source of this dataset? Many thanks.
