### ISSUE TITLE
Temporal Consistency

### ISSUE THREAD

**Issue by Harry-OBrien** [compphoto/Intrinsic#4]
I've understood that the paper is intended for use on single images. Hence, applying the work to a video results in flashes and artefacts over the course of the video. I'll attach an example tomorrow. Have you attempted any methods to make your model temporally consistent or any quick fixes that/ideas on how one might approach this problem?

**Comment by CCareaga** [comment]
There is no easy trick to fix the temporal inconsistency that we know of, but it's definitely something that would be nice to have. One thing that can help is making sure all of the per-frame decompositions are on the same scale (e.g. match all the albedo components with least squares). This won't get rid of the flickering though as there are local inconsistencies that happen between frames. I know there are off-the-shelf solutions to de-flickering but we haven't tested them.
