### ISSUE TITLE
where can we download the model weights

### ISSUE THREAD

**Issue by JonathanBrok** [compphoto/Intrinsic#5]
running the image decomposition pipeline script, it assumes a 'final_weights.pt' file is saved somewhere, but I did not find it

Thanks,
Jonathan

**Comment by CCareaga** [comment]
Hi Jonathan,

By default the decompose script will use the weights from the paper, the script will download these weights automatically the first time you run it using PyTorch Hub functionality: 

https://github.com/compphoto/Intrinsic/blob/d9741e99b2997e679c4055e7e1f773498b791288/intrinsic/model_util.py#L25 

If for some reason they don't download properly you could do it manually, the weights are stored in one of the repo's releases: 

https://github.com/compphoto/Intrinsic/releases/tag/v1.0

Download the final_weights.pt file, then in the decompose.py script load the models with:

```models = load_models('/path/to/final_weights.pt')```

Let me know if you have any issues getting it working, I'm curious as to why the weights didn't download automatically.

**Comment by JonathanBrok** [comment]
Thanks for the prompt reply chris, and also for providing the code - after noting that the collab calls the model loading with a different string, I performed the following which solved my issue

# models = load_models('final_weights.pt')
models = load_models('paper_weights')

all the best

**Comment by CCareaga** [comment]
Ah I see, yeah that makes sense, using that string triggers the automatic downloading. Glad you got it figured out 👍
