### ISSUE TITLE
Weights loading issue

### ISSUE THREAD

**Issue by banterle** [compphoto/Intrinsic#6]
Thank you for this great work. I am trying to use both paper weights and rendered weights, but I get this issue:

 File "/home/user/Intrinsic/intrinsic/model_util.py", line 40, in load_models
    iid_model.load_state_dict(iid_state_dict)
  File "/home/user/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MidasNet_small:
        size mismatch for scratch.layer2_rn.weight: copying a param with shape torch.Size([128, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 48, 3, 3]).

**Comment by CCareaga** [comment]
Thanks for bringing this to my attention, it looks like I broke things in another codebase that this repo depends on. I have fixed the error and the model loading should work correctly now. Let me know if the issue persists.

**Comment by banterle** [comment]
I tried it but it still does not work. By the way I fixed it by adding this line before loading the dictionary:
 iid_model.scratch.layer2_rn = torch.nn.Conv2d(48, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)

It would be nice to have an eval.py in the github package to evaluate the model and save results locally. So I extended a bit the example in the readme.md:
[eval.txt](https://github.com/user-attachments/files/16796775/eval.txt)

**Comment by CCareaga** [comment]
Did you re-install the dependencies? It was just a problem with [these lines](https://github.com/CCareaga/MiDaS/blob/0a450fbb5d42fec82a9bb5131c4f7a3c44dbd272/altered_midas/blocks.py#L178-L180) being deleted in my model code repo. I'm able to run things without error on the [colab notebook](https://colab.research.google.com/github/compphoto/Intrinsic/blob/main/intrinsic_inference.ipynb). 

I can add an eval script to the repo as you said, thank you for the suggestion.

**Comment by banterle** [comment]
>>Did you re-install the dependencies? 
I think so, I will re-check tomorrow deleting the env just to be 100% sure.

>>I'm able to run things without error on the [colab notebook](https://colab.research.google.com/github/compphoto/Intrinsic/blob/main/intrinsic_inference.ipynb).

For now, I did some tests by redefining scratch.layer2_rn, and your method works very well, I haven't seen such a robust method before. Also the theory is pretty neat, well done and thank you for sharing such nice work!

>>I can add an eval script to the repo as you said, thank you for the suggestion.
You are welcome, I think it would be nice, but it's up to you.

**Comment by CCareaga** [comment]
Thank you, glad you find it useful! Let me know if there are any other issues you run into, I'll close the issue.
